export enum WSPacketType {
  REVIEW = "REVIEW",

  SERVER_STATUS = "SERVER_STATUS",

  ONLINE_NUMBER = "ONLINE_NUMBER",

  WHISPER = "WHISPER",

  SESSION_RESPONSE = "SESSION_RESPONSE",

  SESSION_REQUEST = "SESSION_REQUEST",

}
